default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432 

development: 
  <<: *default
  database: QuoteManager_development

test: 
  <<: *default
  database: QuoteManager_test

production:
 <<: *default
 database: QuoteManager_production
 username: quotemanager
 password: <%= ENV['QUOTEMANAGER_DATABASE_PASSWORD'] %>

staging:
 <<: *default
 database: QuoteManager_staging
